FROM ubuntu:latest

COPY mangle_web_engine /mangle_web_engine
COPY Rocket.toml /Rocket.toml

# RUN apt update -y && \
#     apt upgrade -y && \
#     apt install snapd -y && \
#     snap install core && \
#     snap refresh core && \
#     snap install --classic certbot && \
#     ln -s /snap/bin/certbot /usr/bin/certbot